### ISSUE TITLE
Painted Blocks Not Functional

### ISSUE THREAD

**Issue by InsomniaKitten** [Eladkay/PaintATT#2]
The item model of the painted block does not change, and places as the original block in the world, with no custom texture.

**Mod version:** [1.0](https://minecraft.curseforge.com/projects/paint-all-the-things/files/2524593)

![screenshot_item](https://i.imgur.com/S5w7VrN.png)
![screenshot_world](https://i.imgur.com/bRY6I4n.png)

**Comment by Eladkay** [comment]
Could be it's just with sponge? I'll test later and add it to the list of invalid blocks if that is the case. Have you gotten around to trying it with other paint blocks?

**Comment by InsomniaKitten** [comment]
I've never touched Sponge in my entire life.

**Comment by Eladkay** [comment]
Can't replicate indev with the exact same setup... Can you let me know after the new update?
