### ISSUE TITLE
Machine Does Not Drop Contents When Broken

### ISSUE THREAD

**Issue by InsomniaKitten** [Eladkay/PaintATT#4]
When breaking the painting machine with contents in its slots, the contents is not dropped in the world.

**Mod version:** [1.0](https://minecraft.curseforge.com/projects/paint-all-the-things/files/2524593)

**Comment by Eladkay** [comment]
I’ll go and call it a liblib bug, because liblib should be doing that for me.

@yrsegal @thecodewarrior
