### ISSUE TITLE
Hotbar Slots Have Incorrect Positions

### ISSUE THREAD

**Issue by InsomniaKitten** [Eladkay/PaintATT#5]
The hotbar slots in the painting machine GUI are in the wrong positions.

**Mod version:** [1.0](https://minecraft.curseforge.com/projects/paint-all-the-things/files/2524593)

![screenshot](https://i.imgur.com/PBeTZC2.png)

**Comment by Eladkay** [comment]
Files in with GUI issues: @thecodewarrior @Bluexin

**Comment by Bluexin** [comment]
This should have been fixed in liblib a few weeks ago. Could you try with
latest liblib release?

**Comment by Eladkay** [comment]
I hope everyone is running the latest liblib build from curseforge...

**Comment by xAlicatt** [comment]
I just tested with the very latest build from today, and my hotbar is still way out from where it's supposed to be. https://imgur.com/a/FPWLk

**Comment by Bluexin** [comment]
Oh didn't see it went below.
I guess someone tried to fix what I already fixed, making it be offset
twice >.<
I'll just throw a rant in liblib dev channel.
