### ISSUE TITLE
No Output When Processing 1 Item

### ISSUE THREAD

**Issue by InsomniaKitten** [Eladkay/PaintATT#6]
When trying to process a single item, the output slot remains empty after progress reaches 100%.

**Mod version:** [1.0](https://minecraft.curseforge.com/projects/paint-all-the-things/files/2524593)

**Comment by Eladkay** [comment]
Paul suggested a fix in the wizardry channel.

Putting it here so I don't forget: 
In your TilePaintingMachine#tick method, you extract the item input and then try to get the input item stack in that slot again in the line after.(edited)
The code should be using the return of extractItem
