### ISSUE TITLE
Retexturing issues

### ISSUE THREAD

**Issue by xAlicatt** [Eladkay/PaintATT#8]
I have over 270 mods in my personal pack, so it would take me a long time to pinpoint what is causing this incompatibility.

I'm getting weird texture issues with painted blocks.

https://i.imgur.com/HaQVx7n.png

This is glowstone on the left and brick stairs on the right, both supposed to be painted as red sandstone.

**Comment by xAlicatt** [comment]
Seems to be happening with other textures as well.

**Comment by xAlicatt** [comment]
Same thing happening with painted fences.

**Comment by Eladkay** [comment]
That’s weird, I’ve always been testing with fences. I’ll test it later today and fix it

**Comment by Eladkay** [comment]
There seems to be an unusually strong correlation between this and #3. I'll solve that first and then get back to this.
